### ISSUE TITLE
Unable to install package edge-tts==4.0.3

### ISSUE THREAD

**Issue by ruicai83** [hasscc/hass-edge-tts#2]
Hi,
**issue:**
can't install edge_tts
**log:**
Unable to install package edge-tts==4.0.3: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f8e59a6d0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/97/94/bdacfe5da5c920004229fb4ec9c9ad144131c368538c763e074a0609ab82/edge_tts-4.0.3-py3-none-any.whl WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f8e59a9a0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/97/94/bdacfe5da5c920004229fb4ec9c9ad144131c368538c763e074a0609ab82/edge_tts-4.0.3-py3-none-any.whl WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f8e59ac10>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/97/94/bdacfe5da5c920004229fb4ec9c9ad144131c368538c763e074a0609ab82/edge_tts-4.0.3-py3-none-any.whl WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f8e59adf0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/97/94/bdacfe5da5c920004229fb4ec9c9ad144131c368538c763e074a0609ab82/edge_tts-4.0.3-py3-none-any.whl WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f8e59af40>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/97/94/bdacfe5da5c920004229fb4ec9c9ad144131c368538c763e074a0609ab82/edge_tts-4.0.3-py3-none-any.whl ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/97/94/bdacfe5da5c920004229fb4ec9c9ad144131c368538c763e074a0609ab82/edge_tts-4.0.3-py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f8ebb4040>: Failed to establish a new connection: [Errno -2] Name does not resolve')) WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

**HA version:**
Home Assistant 2022.5.0.dev20220414

**Comment by al-one** [comment]
> Failed to establish a new connection: [Errno -2] Name does not resolve

Check your network and dns servers.
