### ISSUE TITLE
edge-tts 5.0.2 and 5.0.3 CI/CD fails for some reason

### ISSUE THREAD

**Issue by rany2** [hasscc/hass-edge-tts#20]
* https://github.com/hasscc/hass-edge-tts/actions/runs/3134559508/jobs/5089277117
* https://github.com/hasscc/hass-edge-tts/actions/runs/3134515895/jobs/5089147553

**Comment by al-one** [comment]
Maybe it's too close to the upstream release. 🤣

**Comment by rany2** [comment]
Does home assistant have some dependency on aiohttp?

**Comment by al-one** [comment]
Yes.

**Comment by rany2** [comment]
These version updates aren't a big deal anyway. Only difference is I pinned aiohttp version and setup code scanning/dependabot/dependency graph, but considering the issue with hass-edge-tts I will stop pinning aiohttp and pick the latest version that works fine with edge-tts/doesn't have any vulnerabilities.

Thanks!
