### ISSUE TITLE
I can't get this to work.

### ISSUE THREAD

**Issue by wptracy** [hasscc/hass-edge-tts#36]
I can't get this to work.
Alexa complains, says:
Sorry, text to speech can only be called with the notify dot Alexa underscore media service. Please see the Alexa underscore media wiki for details.

Home Assistant 2023.1.7 
Supervisor 2023.01.1 
Operating System 9.5 
Frontend 20230110.0 - latest 

```
[core-ssh custom_components]$ wget -O - https://raw.githubusercontent.com/hasscc/get/main/get | DOMAIN=edge_tts REPO_PATH=hasscc/hass-edge-tts ARCHIVE_TAG=main bash -
Connecting to raw.githubusercontent.com (185.199.109.133:443)
writing to stdout
-                    100% |********************************|  3970  0:00:00 ETA
written to stdout
INFO: Archive URL: https://github.com/hasscc/hass-edge-tts/archive/main.zip
INFO: Trying to find the correct directory...
INFO: Found Home Assistant configuration directory at '/config'
INFO: Changing to the custom_components directory...
INFO: Downloading...
Connecting to github.com (140.82.114.4:443)
Connecting to codeload.github.com (140.82.113.10:443)
saving to '/config/custom_components/main.zip'
main.zip             100% |********************************|  8333  0:00:00 ETA
'/config/custom_components/main.zip' saved
INFO: Unpacking...
INFO: Removing temp files...
INFO: Installation complete.
INFO: 安装成功！

INFO: Remember to restart Home Assistant before you configure it.
INFO: 请重启 Home Assistant
[core-ssh custom_components]$ 

[core-ssh custom_components]$ ls
alexa_media  edge_tts     hacs         xiaomi_miot
[core-ssh custom_components]$ ls edge_tts/
__init__.py    manifest.json  tts.py
[core-ssh custom_components]$ 

restarted, then:
added edge_tts to configuration.yaml:

# Text to speech
tts:
  - platform: google_translate

  - platform: edge_tts
    language: en-US # Default language or voice (Optional)
    
test in Developer Tools:

service: tts.edge_tts_say
data:
  entity_id: media_player.william_s_office_echo_dot
  message: >-
    You can replace this text with any text you wish. You can either write in
    this text box or paste your own text here.  Try different languages and
    voices. Change the speed and the pitch of the voice. You can even tweak the
    SSML (Speech Synthesis Markup Language) to control how the different
    sections of the text sound. Click on SSML above to give it a try!  Enjoy
    using Text to Speech!
  options:
    voice: Eric (neural)
```
Alexa complains, says:
Sorry, text to speech can only be called with the notify dot Alexa underscore media service. Please see the Alexa underscore media wiki for details.

**Comment by rany2** [comment]
@al-one Is this related to https://github.com/hasscc/hass-edge-tts/issues/33?

**Comment by wptracy** [comment]
I deleted google_translate, but it still didn't work.
tts:
  - platform: google_translate

**Comment by rany2** [comment]
In `entity_id` replace `media_player` with `notify.alexa_media`.

**Comment by wptracy** [comment]
Like this?

service: tts.edge_tts_say
data:
  entity_id: notify.alexa_media.william_s_office_echo_dot
  message: >-
    You can replace this text with any text you wish. You can either write in
    this text box or paste your own text here.  Try different languages and
    voices. Change the speed and the pitch of the voice. You can even tweak the
    SSML (Speech Synthesis Markup Language) to control how the different
    sections of the text sound. Click on SSML above to give it a try!  Enjoy
    using Text to Speech!
  options:
    voice: Eric (neural)

![image](https://user-images.githubusercontent.com/78648145/216138659-0b65ac1f-8667-468e-b427-10ae43d3d6f0.png)

**Comment by rany2** [comment]
@wptracy Could you check these links:

- https://github.com/custom-components/alexa_media_player/wiki/FAQ#ive-just-upgraded-now-tts-isnt-working
- https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Notification-Component

It appears that this is a change in [alexa_media_player](https://github.com/custom-components/alexa_media_player)

**Comment by rany2** [comment]
> Like this?

I'm not entirely sure, but I think the links match the issue you're facing.

**Comment by rany2** [comment]
> voice: Eric (neural)

P.S. your voice is invalid. It should be `en-US-EricNeural`.

**Comment by wptracy** [comment]
This is in my automation, and it works.

service: notify.alexa_media_william_s_office_echo_dot
data:
  message: Shelly Flood Detected Water

I replaced 
entity_id: notify.alexa_media.william_s_office_echo_dot
with
entity_id: notify.alexa_media_william_s_office_echo_dot
And Alexa doesn't say anything.

service: tts.edge_tts_say
data:
  entity_id: notify.alexa_media_william_s_office_echo_dot
  message: >-
    You can replace this text with any text you wish. You can either write in
    this text box or paste your own text here.  Try different languages and
    voices. Change the speed and the pitch of the voice. You can even tweak the
    SSML (Speech Synthesis Markup Language) to control how the different
    sections of the text sound. Click on SSML above to give it a try!  Enjoy
    using Text to Speech!
  options:
    voice: Eric (neural)

**Comment by rany2** [comment]
I'm sorry but I don't think anyone here might be able to help you but there is also this thread with people with similar issues: https://github.com/custom-components/alexa_media_player/issues/1683

**Comment by wptracy** [comment]
I changed voice and tried again.
Alexa still complains.

 Text to speech
tts:
  - platform: google_translate

  - platform: edge_tts
    language: en-US-EricNeural # Default language or voice (Optional)

service: tts.edge_tts_say
data:
  message: >-
    You can replace this text with any text you wish. You can either write in
    this text box or paste your own text here.  Try different languages and
    voices. Change the speed and the pitch of the voice. You can even tweak the
    SSML (Speech Synthesis Markup Language) to control how the different
    sections of the text sound. Click on SSML above to give it a try!  Enjoy
    using Text to Speech!
  options:
    voice: EricNeural
  entity_id: media_player.william_s_office_echo_dot

**Comment by wptracy** [comment]
Where is you find the acceptable voice like en-US-EricNeural
Is there a list?

**Comment by rany2** [comment]
I honestly haven't use HASS in a while (I only maintain the [edge-tts](https://github.com/rany2/edge-tts) library which this uses) but the list is accessible from https://github.com/hasscc/hass-edge-tts/blob/main/custom_components/edge_tts/tts.py#L24 or https://speech.platform.bing.com/consumer/speech/synthesize/readaloud/voices/list?trustedclienttoken=6A5AA1D4EAFF4E9FB37E23D68491D6F4 (either `ShortName` or `Name` would work)

**Comment by wptracy** [comment]
This was working all along.  I just didn't know how to use is.
These are the currently supported media plays for Home Assistant.
https://www.home-assistant.io/integrations/media_player/
Currently only supported on [Sonos](https://www.home-assistant.io/integrations/sonos), [Spotify](https://www.home-assistant.io/integrations/spotify), [MPD](https://www.home-assistant.io/integrations/mpd), [Kodi](https://www.home-assistant.io/integrations/kodi), [Roon](https://www.home-assistant.io/integrations/roon), [Owntone](https://www.home-assistant.io/integrations/forked_daapd), [Squeezebox](https://www.home-assistant.io/integrations/squeezebox) and [Universal](https://www.home-assistant.io/integrations/universal).

The Edge TTS card appears in the Media TTS Card. 
It plays on supported devices.
![Screenshot from 2023-02-03 14-43-16](https://user-images.githubusercontent.com/78648145/216716633-079093e7-600f-4903-ab9f-ae8cb394fbc2.png)
![Screenshot from 2023-02-03 14-43-08](https://user-images.githubusercontent.com/78648145/216716653-9af4ab3e-d824-4a2e-bb76-94d81ffbc9fc.png)

**Comment by rany2** [comment]
So this is solved?

**Comment by wptracy** [comment]
yes
