### ISSUE TITLE
Female voice is not working after latest update

### ISSUE THREAD

**Issue by haralake** [hasscc/hass-edge-tts#39]
After latest update only el-GR-NestorasNeural voice is working. The female voice el-GR-AthinaNeural doesnt work and is giving this error:

`Edge TTS: failed: ["Test TTS", {'platform': 'edge_tts', 'language': 'el-GR', 'cache': True, 'time_memory': 300, 'cache_dir': 'tts', 'voice': 'el-GR-AthinaNeural', 'rate': '+0%', 'volume': '+1%'}]`

**Comment by rany2** [comment]
Update has nothing to do with it, if you check the voice list it was removed.

**Comment by haralake** [comment]
As i see both are supported:
![Screenshot_1](https://user-images.githubusercontent.com/18325407/236497096-82c88c32-1f50-46bb-b472-eddabdcb6cc1.png)

**Comment by haralake** [comment]
I see. Very weird, i used this voice normaly until yesterday.

**Comment by rany2** [comment]
Maybe it's coming back and it's just an intermittent issue on their end. We'll have to wait and see

**Comment by haralake** [comment]
Thank you!

**Comment by rany2** [comment]
I've tried this today out of curiosity and indeed it seems to have been fixed by Microsoft. Closing.
