### ISSUE TITLE
提示no tts from edge_tts for ……

### ISSUE THREAD

**Issue by bokeylee** [hasscc/hass-edge-tts#8]
<img width="587" alt="截屏2022-06-16 14 25 52" src="https://user-images.githubusercontent.com/63947149/174005618-2e4e97ab-d4f6-443f-bc38-bf3d321de6e7.png">
提示no tts from edge_tts for ……
本来大半年一直用的好好的，今天突然就不行了

**Comment by sasukebinbin** [comment]
我的也是. 发现是style出现问题了,只要不加style就没有问题

**Comment by zhangguangjin** [comment]
楼上的朋友，我也是同样的问题，我去掉style还是不行，你能贴个具体的配置来参考下吗？

**Comment by zhangguangjin** [comment]
> 我的也是.发现是style出现问题了，只要不加style就没有问题

楼上的朋友，我也是同样的问题，我去掉style还是不行，你能贴个具体的配置来参考下吗？

**Comment by rany2** [comment]
Hey everyone, I'm the edge-tts mainainer.

Any custom SSML which has the following characteristics is now blocked including:
* anything with mstts prefix, 
* anything that uses multiple voices in one SSML document
* anything that uses an advanced prosody feature (basically anything other than pitch, rate, volume)
* anything that uses the break element
* most likely a lot more....

I think it's better to avoid custom SSML entirely

**Comment by rany2** [comment]
Just to be clear it's not my decision, Microsoft noticed and blocked it. I cannot do anything.

**Comment by rany2** [comment]
I have removed custom SSML support from the library in 5.0.0. Sorry everyone! https://github.com/rany2/edge-tts/commit/68a9e191d7b00c424fe137390254a7a5c8e41db7

**Comment by bokeylee** [comment]
thanks for @rany2 @al-one 's helping. problem has been sloved. 
感谢二位大佬！
**For homeassistant user:**
remove custom 'style', 'styledegree', 'role', 'contour' in _configulation.yaml_
HASS用户把_configulation.yaml_中的语音风格、角色等属性移除即可，只保留单纯的语言设置。
@zhangguangjin 
easy sample:
`tts:
  - platform: edge_tts
    language: zh-CN`
custom voice is supported as well:
也可以继续自定义特定的发音人：
`tts:
  - platform: edge_tts
    language: zh-CN-XiaoxiaoNeural`
